Homeworks 15
Alex-Shev75/Python_homework_repository pull request #2
Opened 2023-02-22 21:43 UTC by Alex-Shev75

added hw_15

2023-02-22 21:44 UTC, Alex-Shev75 commented
Oleksii, check pls

2023-02-26 16:31 UTC, klymenok requested changes
Taks 3 is missing

2023-02-27 18:49 UTC, Alex-Shev75 commented
task 3 added, pls check

2023-02-28 20:33 UTC, klymenok approved these changes
Looks good!

2023-05-08 20:04 UTC, merged